name: Tests

on:
  push:
    branches:
      - master
  pull_request: ~
  schedule:
    - cron: 0 0 1 * * # Monthly
  workflow_dispatch:  # Run this workflow manually from the Actions tab

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
        symfony:
          - '4.1.*'
          - '5.0.*'
          - '6.0.*'
        exclude:
          - php: '8.0'
            symfony: '4.1.*'
          - php: '8.1'
            symfony: '4.1.*'
          - php: '7.4'
            symfony: '6.0.*'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl

      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Update project dependencies
        run: composer update --no-progress --prefer-dist --no-interaction

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: Run tests
        run: APP_DEBUG=0 SYMFONY_DEPRECATIONS_HELPER='max[direct]=0' ./vendor/bin/simple-phpunit
